In [2]:
from __future__ import print_function
import torch 

In [31]:
x = torch.empty(0,28)
x

tensor([])

In [9]:
x = torch.empty(5005,)
x

tensor([0., 0., 0.,  ..., 0., 0., 0.])

In [10]:
x = torch.zeros(5005,)
x

tensor([0., 0., 0.,  ..., 0., 0., 0.])

In [11]:
x = torch.rand(5005,)
x

tensor([0.9161, 0.8709, 0.2697,  ..., 0.9112, 0.7475, 0.5384])

In [12]:
x.shape

torch.Size([5005])

In [22]:
import numpy as np
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [29]:
x = torch.tensor(x)
x

tensor([1, 2, 3, 4])